### PR TITLE
chageDoiState method

### PR DESCRIPTION
**Pull request by rdpaorg**
stageDoi method accepts events: "publish" (to move a doi to findable state), "hide" (to move a doi form published to registered state), and "register" (to move a doi from draft to registered state)

### CODE REVIEW

**Review by andrewbrazzatti — CHANGES_REQUESTED** [review]
Please change the function name to changeDoiState to better describe it's function.

Also this function needs some integration tests written for it. See https://github.com/redbox-mint/redbox-portal/blob/master/test/unit/services/DOIService.test.js for other DOI tests

**Comment by rdpaorg** [comment]
The method has been renamed, the unit tests added.
N.B. : now two test draft DOIs are created. The second one is for state changes. It will be kept as "registered" as it can't be deleted.

**Comment by andrewbrazzatti** [comment]
Hey @rdpaorg, it would be good to test publish every build but we'd end up with potentially 1000s of DOIs that are undeletable in the account. As this account has been donated to us by one of our customers that use it for other manual testing processes this will make things difficult for them. 
Can you please comment out the publish test so we can run it when we need to and ensure that the DOI is deleted so that we clean it all up?

Thanks

**Comment by rdpaorg** [comment]
The datacite staging tests have been commented out.

**Pull request merged**
